version: '3.8'
services:
    townhall-service: # rename this to something like <yourservicename>-service
        build: .
        image: developmentbydavid/prytaneum-townhall:beta
        volumes:
            - ./src:/usr/app/src
        ports:
            - '3000:3000'
        depends_on:
            - mongo
            - rabbitmq
    mongo:
        image: mongo:4.2.8-bionic
    rabbitmq:
        image: rabbitmq:3.8.5
